services :
  pozos-registry:
    image: registry:2.8.1
    container_name: pozos-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker/registry:/var/lib/registry
      - ./registry/auth:/auth
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd 
    command: 
      - /bin/sh
      - -c
      - 'apk add --no-cache apache2-utils && htpasswd -Bbn pozos pozos > /auth/htpasswd &&  registry serve /etc/docker/registry/config.yml'
    networks:
      - pozos-registry-networks

  frontend-registry:
    image: joxit/docker-registry-ui:2
    container_name: frontend-registry
    ports:
      - "8080:80"
    environment:
      - NGINX_PROXY_PASS_URL=http://pozos-registry:5000
      - REGISTRY_TITLE=Pozos 
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true

    networks:
      - pozos-registry-networks
    depends_on:
      - pozos-registry
  
networks:
  pozos-registry-networks:  
    driver: bridge
    name: pozos-registry-networks